//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Audio .
        /// </summary>
        internal static string DownloadAudio {
            get {
                return ResourceManager.GetString("DownloadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔️ Downloaded audio!.
        /// </summary>
        internal static string DownloadedAudio {
            get {
                return ResourceManager.GetString("DownloadedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔️ Downloaded video!.
        /// </summary>
        internal static string DownloadedVideo {
            get {
                return ResourceManager.GetString("DownloadedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕓 Now downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video (Highest Quality).
        /// </summary>
        internal static string DownloadVideo {
            get {
                return ResourceManager.GetString("DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕓 Fetching video info....
        /// </summary>
        internal static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits to the icon creators on flaticon.com.
        /// </summary>
        internal static string Flaticon {
            get {
                return ResourceManager.GetString("Flaticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found video info!.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re checking the source code. oh no!.
        /// </summary>
        internal static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Could not find video info!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is getting dark out here!.
        /// </summary>
        internal static string ToDark {
            get {
                return ResourceManager.GetString("ToDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displaying in plain english!.
        /// </summary>
        internal static string ToEnglish {
            get {
                return ResourceManager.GetString("ToEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello to the kurdish-speaking one!.
        /// </summary>
        internal static string ToKurdish {
            get {
                return ResourceManager.GetString("ToKurdish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is bright again!.
        /// </summary>
        internal static string ToLight {
            get {
                return ResourceManager.GetString("ToLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string VidAuthor {
            get {
                return ResourceManager.GetString("VidAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string VidDuration {
            get {
                return ResourceManager.GetString("VidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string VidTitle {
            get {
                return ResourceManager.GetString("VidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the download format.
        /// </summary>
        internal static string WaitingFormat {
            get {
                return ResourceManager.GetString("WaitingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give the URL of the video.
        /// </summary>
        internal static string WaitingURL {
            get {
                return ResourceManager.GetString("WaitingURL", resourceCulture);
            }
        }
    }
}
